server:
  port: 8010

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://PAYMENTSERVICEJAN25
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: myJwtSecretKey123456
